apiVersion: v1
kind: Service
metadata:
  name: www-nginx-service
  namespace: example
spec:
  type: LoadBalancer
  selector:
    app: www-nginx
  ports:
    - protocol: TCP
      name: www-nginx
      port: 8080
      targetPort: 80