apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: portainer-storage
  local:
    path: /opt/portainer-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - earth
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portainer-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
